### ISSUE TITLE
Bolt won't reset

### ISSUE THREAD

**Issue by smartsoldier** [gemforce-team/Autocast#1]
I understand you have to manually (re)move the spells, and the freeze spell works fine, but the Bolt spell worked perfect the first time / level and now the hotkey ctrl+4 does nothing. I dont get the little text popup and it doesn't setup the autocast.

**Comment by hellrage** [comment]
Hello! Only strike spells are supported, it shouldn't have had any effect with bolt even the first time.
I missed a few sentences where I clarify that in the readme, will fix.
